version: '3.7'
services:

  discovery:
    image: sviat-H/docker:docker-discovery-server
    container_name: discovery
    restart: on-failure
    ports:
      - 8761:8761
    network_mode: host

  config:
    image: sviat-H/docker:docker-config-server
    container_name: config
    network_mode: host
    depends_on:
      - discovery
    ports:
    - 8888:8888

  account:
    image: sviat-H/docker:docker-account-service
    container_name: account
    restart: on-failure
    network_mode: host
    depends_on:
      - discovery
      - config
    ports:
    - 8081:8081

  profile:
    image: sviat-H/docker:docker-profile-service
    container_name: profile
    restart: on-failure
    network_mode: host
    depends_on:
      - discovery
      - config
    ports:
    - 8082:8082
